# Manifests produced by scripts in src/data/*.py
train_manifest: data/processed/train_bd.jsonl
valid_manifest: data/processed/valid_bd.jsonl
# Optional baseline (mixed accent) for comparison
baseline_manifest: data/processed/valid_mixed.jsonl

# Audio params
sample_rate: 22050
n_mels: 80
fmin: 0
fmax: 8000
n_fft: 1024
hop_length: 256
win_length: 1024

# Tokenization / phonemes
use_phonemes: false
phonemizer_lang: bn