seed: 42
project_name: bd_bangla_tts

learning_rate: 1.0e-4
batch_size: 2
num_epochs: 1
warmup_steps: 0
gradient_accumulation_steps: 1
mixed_precision: false
save_strategy: steps
save_steps: 50
eval_steps: 50
max_steps: null

progressive_unfreeze:
  - { module: 'vits', epoch: 0 }    # keep simple on CPU
  - { module: 'adapter', epoch: 0 }

output_dir: outputs/tts
log_dir: outputs/logs
checkpoint_dir: outputs/checkpoints
accent_clf_ckpt: outputs/accent_clf/random_forest.joblib

wandb:
  enabled: false
  entity: null
  project: bd_bangla_tts
