seed: 42
project_name: bd_bangla_tts

learning_rate: 1.0e-4
batch_size: 2
num_epochs: 2
warmup_steps: 0
gradient_accumulation_steps: 1
mixed_precision: true       # will auto-disable on CPU
save_strategy: steps
save_steps: 50
eval_steps: 20
max_steps: null

progressive_unfreeze:
  - { module: 'adapter', epoch: 0 }
  - { module: 'disc', epoch: 0 }
  - { module: 'vits.text_encoder', epoch: 2 }
  - { module: 'vits.generator', epoch: 4 }

output_dir: outputs/tts
log_dir: outputs/logs
checkpoint_dir: outputs/checkpoints
accent_clf_ckpt: outputs/accent_clf/random_forest.joblib

wandb:
  enabled: false          # avoid Windows console unicode issues
  entity: null
  project: bd_bangla_tts

sample_every_steps: 50
sample_text: "আমি বাংলাদেশ থেকে এসেছি।"
